name: Deploy to Production

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add your deployment steps here
      - name: Deploy to production
        run: echo "Deploying to production"
