name: Deploy to Production

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add your deployment steps here
      - name: Deploy to production
        run: echo "Deploying to production"

  block:
    if: !startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Skip deployment
        run: echo "Deployment skipped because branch is not from feature/*"
